CREATE SEQUENCE employee_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE supplier_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE material_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE supply_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE usage_seq START WITH 1 INCREMENT BY 1;
